import "../styles/globals.css";
import "nprogress/nprogress.css";
import type { AppProps } from "next/app";
import Head from "next/head";
import dynamic from "next/dynamic";
import { Provider } from "react-redux";
import store from "store";
import { ethereumClient, wagmiClient } from "config/walletModalConfig";
import { Web3Modal } from "@web3modal/react";
import { WagmiConfig } from "wagmi";
import { useEffect, useState } from "react";
// import { SessionProvider } from "next-auth/react";
import { createTheme, ThemeProvider } from "@mui/material";
import Notifications from "components/shared/Notifications";
import { useImmediateNotifications } from "hooks/useImmediateNotifications";

const theme = createTheme({
  palette: {
    mode: "dark",
    primary: {
      main: "#6456dc",
    },
  },
  // disableButtonFocusRipple
  components: {
    MuiButtonBase: {
      defaultProps: {
        disableRipple: true,
      },
    },
  },
});

const TopProgressBar = dynamic(
  () => {
    return import("components/shared/TopProgressBar");
  },
  { ssr: false }
);

function MyApp({ Component, pageProps: { session, ...pageProps } }: AppProps) {
  const [isMounted, setIsMounted] = useState(false);
  useImmediateNotifications();

  useEffect(() => {
    setIsMounted(true);
  }, []);

  return (
    <ThemeProvider theme={theme}>
      <div className="text-white select-none">
        <Head>
          <title>Stable Strategies</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <video
          autoPlay
          muted
          loop
          className="fixed w-auto min-w-full min-h-full -z-10 max-w-none"
        >
          <source src="/bg-video.mp4" type="video/mp4" />
        </video>
        <main>
          <TopProgressBar />
          {isMounted && (
            <Provider store={store}>
              {/* <SessionProvider session={session}> */}
              <WagmiConfig client={wagmiClient}>
                <Component {...pageProps} />
              </WagmiConfig>
              {/* </SessionProvider> */}
            </Provider>
          )}
          <Web3Modal
            ethereumClient={ethereumClient}
            projectId={process.env.NEXT_PUBLIC_WEB3_WALLET_PROJECT_ID}
          />
          <Notifications />
        </main>
      </div>
    </ThemeProvider>
  );
}

export default MyApp;
